name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: pnpm install --frozen-lockfile
        working-directory: package
      - run: pnpm run build
        working-directory: package
      - run: pnpm install --frozen-lockfile && pnpm run test
        working-directory: test
